### PR TITLE
Support weak references

### PR DESCRIPTION
**Pull request by KuraiAndras**

### CODE REVIEW

**Comment by KuraiAndras** [comment]
@OmiCron07 can you try if this would work for you?

**Comment by KuraiAndras** [comment]
I have created tests around garbage collection and it seems to work as intended

**Comment by OmiCron07** [comment]
I changed `courier.Subscribe` for `courier.SubscribeWeak`, but my callback never get called.

**Comment by KuraiAndras** [comment]
I have tried it in the wpf sample and it does not work sadly. I'll look into this

**Comment by KuraiAndras** [comment]
Okay, so the tests now work as expected, and I have tried it with the WPF sample. If you open a new window, close it, press the Run GC button, wait for the gc to actually run(you can see this in the diagnostic window in VS), set a breakpoint in MediatRCoutirer.cs line 45, then press increment again, you can see that the weak invocation list had 4 elements, but only 3 remain because the reference which the window had was garbage collected.

Please try it out and see if it works for you

**Comment by OmiCron07** [comment]
I confirm in your test app that it works as expected. I cannot reproduce that same behaviour in my own app, but I think I have to rework some things to make it works as expected. So, I "approve" the changes 😜

**Comment by KuraiAndras** [comment]
I'll update the docs, then release a new version soon

**Pull request merged**
